[package]
name = "konvoy-konanc"
version.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true

[dependencies]
flate2.workspace = true
konvoy-util.workspace = true
sha2.workspace = true
tar.workspace = true
thiserror.workspace = true
ureq.workspace = true
